"""
This type stub file was generated by pyright.
"""

from typing import TypeVar
from typing import Union

Card = str
Hand = list[Union[Card, str]]

T = TypeVar("T")
Branch = tuple[str, list[Hand]]

def branches_for_some_hands(hands: list[Hand]) -> list[Branch]:
    ...

def branches_for_one_hand(hand: Hand) -> list[Branch]:
    ...

def select_branch(branches: list[Branch]) -> Branch:
    ...

