"""
This type stub file was generated by pyright.
"""

from typing import Union

Card = str
Hand = list[Union[Card, str]]

def rand_start_hands() -> list[Hand]:
    ...

def hand_score(hand: Hand) -> int:
    ...

def hit_to_hand(hand: Hand) -> Hand:
    ...

def split_hand(hand: Hand) -> list[Hand]:
    ...

def is_hand_win(hand: Hand) -> bool:
    ...

def is_hand_lose(hand: Hand) -> bool:
    ...

def print_hand(hand: Hand): # -> None:
    ...

def print_some_hands(hands: list[Hand]): # -> None:
    ...

def sort_hands(hands: list[Hand]) -> list[Hand]:
    ...

def select_one_hand(hands: list[Hand]) -> Hand:
    ...

def hand_game_score(hand: Hand) -> int:
    ...

def is_hand_better_then(it: Hand, other: Hand) -> bool:
    ...

def are_hands_the_same(it: Hand, other: Hand) -> bool:
    ...

def surrender_hand(hand: Hand) -> Hand:
    ...

def is_surrender_hand(hand: Hand) -> bool:
    ...

def is_hand_enabled(hand: Hand) -> bool:
    ...

def is_hand_disabled(hand: Hand) -> bool:
    ...

def all_hands_disabled(hands: list[Hand]) -> bool:
    ...

